<?xml version="1.0" encoding="UTF-8"?><testrun name="BankJavaTest" project="bankjava" tests="6" started="6" failures="0" errors="1" ignored="0">
  <testsuite name="com.school.bankjava.test.BankJavaTest" time="0.275">
    <testcase name="사용자조회_trim" classname="com.school.bankjava.test.BankJavaTest" time="0.193"/>
    <testcase name="계정상세_foreach" classname="com.school.bankjava.test.BankJavaTest" time="0.033">
      <error>org.apache.ibatis.exceptions.PersistenceException: &#13;
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_id' in 'field list'&#13;
### The error may involve com.school.bankjava.mapper.insertAccountDetails-Inline&#13;
### The error occurred while setting parameters&#13;
### SQL: insert into ACCOUNT_DETAILS(account_id, type, amount)   values     (       ?, ?, ?     ), (     ?, ?, ?     ), (     ?, ?, ?     ), (     ?, ?, ?     ), (     ?, ?, ?     ), (     ?, ?, ?     ), (     ?, ?, ?     ), (     ?, ?, ?     ), (     ?, ?, ?     ), (     ?, ?, ?     )&#13;
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_id' in 'field list'&#13;
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:154)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:141)&#13;
	at com.school.bankjava.dao.BankJavaDao.insertAccountDetails(BankJavaDao.java:49)&#13;
	at com.school.bankjava.test.BankJavaTest.계정상세_foreach(BankJavaTest.java:124)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:483)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_id' in 'field list'&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)&#13;
	at com.mysql.jdbc.Util.getInstance(Util.java:381)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1030)&#13;
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)&#13;
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)&#13;
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1936)&#13;
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2060)&#13;
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2542)&#13;
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1734)&#13;
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:995)&#13;
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:44)&#13;
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:69)&#13;
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)&#13;
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:105)&#13;
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:71)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:152)&#13;
	... 26 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="마이바티스의SqlSessionFactory를가져온다_널이아니기를기대한다_그리고_싱글턴패턴체크" classname="com.school.bankjava.test.BankJavaTest" time="0.0"/>
    <testcase name="사용자조회_파라메터가널인경우마지막에가입된사용자조회_choose" classname="com.school.bankjava.test.BankJavaTest" time="0.003"/>
    <testcase name="사용자조회_파라메터가널인경우마지막에가입된사용자조회" classname="com.school.bankjava.test.BankJavaTest" time="0.002"/>
    <testcase name="프로시저호출확인_각각의테이블에서하나씩데이터가증가됨을확인한다" classname="com.school.bankjava.test.BankJavaTest" time="0.044"/>
  </testsuite>
</testrun>
